import { ROUTES } from "@scf/core/constants/routes";
import { useCreateTeam, useUpdateTeam } from "@scaffald/sdk/react";
import {
  TEAM_INVITATION_POLICIES,
  TEAM_VISIBILITIES,
  teamCreateBaseSchema,
  teamCreateSchema,
  teamRoleKeySchema,
} from "@scf/schemas";
import { zodResolver } from "@hookform/resolvers/zod";
import { useToast, useThemeContext } from "@scaffald/ui";
import { useRouter } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { Controller, type Resolver, useForm } from "react-hook-form";
import { ResponsiveSelect } from "@scaffald/ui";
import {
  Button,
  Input,
  Label,
  ScrollView,
  Spinner,
  Text,
  TextArea,
  Row,
  Stack,
} from "@scaffald/ui";
import type { z } from "zod";

import { useTeamFormOptions } from "../hooks/useTeamFormOptions";
import { colors } from "@scaffald/ui/tokens";

type TeamVisibility = (typeof TEAM_VISIBILITIES)[number];
type TeamRoleKey = z.infer<typeof teamRoleKeySchema>;
type TeamInvitationPolicy = (typeof TEAM_INVITATION_POLICIES)[number];

interface TeamFormValues {
  name: string;
  slug?: string;
  purpose?: string;
  visibility: TeamVisibility;
  invitationPolicy: TeamInvitationPolicy;
  description?: string;
  defaultRoleId?: string;
  defaultRoleKey?: TeamRoleKey;
}

export interface TeamInitialData {
  id: string;
  name: string;
  slug?: string | null;
  purpose?: string | null;
  visibility?: TeamVisibility;
  invitationPolicy?: TeamInvitationPolicy;
  description?: unknown;
  defaultRole?: { id: string; key: TeamRoleKey } | null;
  defaultRoleId?: string | null;
  defaultRoleKey?: TeamRoleKey | null;
}

const teamFormSchema = teamCreateBaseSchema.pick({
  name: true,
  slug: true,
  purpose: true,
  visibility: true,
  invitationPolicy: true,
  description: true,
  defaultRoleId: true,
  defaultRoleKey: true,
});

interface TeamFormProps {
  mode: "create" | "edit";
  organizationId: string;
  teamId?: string;
  initialData?: Partial<TeamInitialData>;
  onCancel?: () => void;
  onSuccess?: (team: unknown) => void;
}

function normalizeDescription(value: unknown) {
  if (value === null || value === undefined) return "";
  if (typeof value === "string") return value;
  try {
    return JSON.stringify(value);
  } catch {
    return "";
  }
}

export function TeamForm({
  mode,
  organizationId,
  teamId,
  initialData,
  onCancel,
  onSuccess,
}: TeamFormProps) {
  const { theme } = useThemeContext();
  const router = useRouter();
  const toast = useToast();
  const [hasAutoGeneratedSlug, setHasAutoGeneratedSlug] = useState(
    mode === "create"
  );

  const defaultValues = useMemo<TeamFormValues>(
    () => ({
      name: initialData?.name ?? "",
      slug: initialData?.slug ?? "",
      purpose: initialData?.purpose ?? "",
      visibility:
        (initialData?.visibility as TeamVisibility | undefined) ??
        "organization",
      invitationPolicy: initialData?.invitationPolicy ?? "invite_only",
      description: normalizeDescription(initialData?.description),
      defaultRoleId:
        initialData?.defaultRoleId ?? initialData?.defaultRole?.id ?? undefined,
      defaultRoleKey:
        initialData?.defaultRoleKey ??
        initialData?.defaultRole?.key ??
        "member",
    }),
    [
      initialData?.invitationPolicy,
      initialData?.defaultRole?.id,
      initialData?.defaultRole?.key,
      initialData?.defaultRoleId,
      initialData?.defaultRoleKey,
      initialData?.description,
      initialData?.name,
      initialData?.purpose,
      initialData?.slug,
      initialData?.visibility,
    ]
  );

  const {
    control,
    handleSubmit,
    getValues,
    formState: { errors, isDirty },
    setValue,
    reset,
  } = useForm<TeamFormValues>({
    // SC-59: cast required for @hookform/resolvers v5 — see useFeedbackForm for context.
    resolver: zodResolver(teamFormSchema) as unknown as Resolver<TeamFormValues>,
    defaultValues,
  });

  useEffect(() => {
    reset(defaultValues);
  }, [defaultValues, reset]);

  const { roles, isLoading: isOptionsLoading } = useTeamFormOptions({
    organizationId,
  });

  // Auto-select default role when options load
  useEffect(() => {
    if (roles.length === 0) return;

    const currentRoleId = getValues("defaultRoleId");
    const currentRoleKey = getValues("defaultRoleKey");

    if (currentRoleId && roles.some((role) => role.id === currentRoleId)) {
      if (!currentRoleKey) {
        const currentRole = roles.find((role) => role.id === currentRoleId);
        if (currentRole) {
          setValue("defaultRoleKey", currentRole.key, { shouldValidate: true });
        }
      }
      return;
    }

    const defaultRole = roles.find((role) => role.key === "member") ?? roles[0];
    setValue("defaultRoleId", defaultRole.id, { shouldValidate: true });
    setValue("defaultRoleKey", defaultRole.key, { shouldValidate: true });
  }, [roles, getValues, setValue]);

  const createMutation = useCreateTeam({
    onSuccess: (data) => {
      toast.show({
        title: "Success",
        message: "Team created successfully",
        variant: "success",
      });
      onSuccess?.(data?.team);
      router.push(ROUTES.OFFICE.CMS.TEAMS.path);
    },
    onError: (error: unknown) => {
      const _message =
        error instanceof Error ? error.message : "Failed to create team";
      toast.show({
        title: "Error",
        message: _message,
        variant: "error",
      });
    },
  });

  const updateMutation = useUpdateTeam({
    onSuccess: (data) => {
      toast.show({
        title: "Success",
        message: "Team updated successfully",
        variant: "success",
      });
      onSuccess?.(data?.team);
      router.push(ROUTES.OFFICE.CMS.TEAMS.path);
    },
    onError: (error: unknown) => {
      const _message =
        error instanceof Error ? error.message : "Failed to update team";
      toast.show({
        title: "Error",
        message: _message,
        variant: "error",
      });
    },
  });

  const isSubmitting = createMutation.isPending || updateMutation.isPending;

  const handleNameChange = (value: string) => {
    setValue("name", value, { shouldValidate: true });
    if (mode === "create" && hasAutoGeneratedSlug) {
      const generatedSlug = value
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "");
      setValue("slug", generatedSlug, { shouldValidate: true });
    }
  };

  const handleSlugChange = (value: string) => {
    setHasAutoGeneratedSlug(false);
    setValue("slug", value, { shouldValidate: true });
  };

  const onSubmit = async (values: TeamFormValues) => {
    const selectedRole = roles.find((role) => role.id === values.defaultRoleId);
    const resolvedDefaultRoleKey =
      values.defaultRoleKey ??
      selectedRole?.key ??
      teamRoleKeySchema.parse("member");

    const payloadBase = {
      organizationId,
      name: values.name.trim(),
      slug: values.slug?.trim() || undefined,
      purpose: values.purpose?.trim() || undefined,
      visibility: values.visibility,
      invitationPolicy: values.invitationPolicy,
      description: values.description?.trim() || undefined,
      defaultRoleId: values.defaultRoleId ?? selectedRole?.id,
      defaultRoleKey: resolvedDefaultRoleKey,
    };

    if (mode === "create") {
      const createPayload = teamCreateSchema.parse({
        ...payloadBase,
        metadata: {},
      });
      await createMutation.mutateAsync(
        createPayload as Parameters<typeof createMutation.mutateAsync>[0]
      );
    } else {
      if (!teamId) {
        toast.show({
          title: "Error",
          message: "Missing team identifier for update",
          variant: "error",
        });
        return;
      }
      await updateMutation.mutateAsync({
        id: teamId,
        params: payloadBase as Parameters<
          typeof updateMutation.mutateAsync
        >[0]["params"],
      });
    }
  };

  const visibilityOptions = TEAM_VISIBILITIES.map((value) => ({
    value,
    label: value === "organization" ? "Organization" : "Private",
  }));

  const invitationPolicyOptions = TEAM_INVITATION_POLICIES.map((value) => ({
    value,
    label: value === "invite_only" ? "Invite Only" : "Request to Join",
  }));

  const renderContent = () => (
    <Stack gap={16} width="100%" maxWidth={640} alignSelf="center">
      <Controller
        name="name"
        control={control}
        render={({ field }) => (
          <Stack gap={8}>
            <Label htmlFor="team-name">Name *</Label>
            <Input
              id="team-name"
              testID="team-form-name"
              value={field.value}
              onChangeText={handleNameChange}
              placeholder="Field Ops Team"
              style={{
                borderColor: errors.name
                  ? theme === "light"
                    ? colors.error[300]
                    : colors.error[700]
                  : colors.border[theme].default,
              }}
            />
            {errors.name && (
              <Text
                style={{
                  color:
                    theme === "light" ? colors.error[700] : colors.error[300],
                }}
              >
                {errors.name.message}
              </Text>
            )}
          </Stack>
        )}
      />

      <Controller
        name="slug"
        control={control}
        render={({ field }) => (
          <Stack gap={8}>
            <Label htmlFor="team-slug">Vanity URL *</Label>
            <Input
              id="team-slug"
              testID="team-form-slug"
              value={field.value ?? ""}
              onChangeText={handleSlugChange}
              placeholder="field-ops-team"
              style={{
                borderColor: errors.slug
                  ? theme === "light"
                    ? colors.error[300]
                    : colors.error[700]
                  : colors.border[theme].default,
              }}
            />
            <Text style={{ color: colors.text[theme].secondary }}>
              Lowercase, URL-friendly username for the team
            </Text>
            {errors.slug && (
              <Text
                style={{
                  color:
                    theme === "light" ? colors.error[700] : colors.error[300],
                }}
              >
                {errors.slug.message}
              </Text>
            )}
          </Stack>
        )}
      />

      <Controller
        name="purpose"
        control={control}
        render={({ field }) => (
          <Stack gap={8}>
            <Label htmlFor="team-purpose">Purpose</Label>
            <Input
              id="team-purpose"
              testID="team-form-purpose"
              value={field.value ?? ""}
              onChangeText={(value) => field.onChange(value)}
              placeholder="e.g. Hiring for Southeast operations"
            />
            {errors.purpose && (
              <Text
                style={{
                  color:
                    theme === "light" ? colors.error[700] : colors.error[300],
                }}
              >
                {errors.purpose.message}
              </Text>
            )}
          </Stack>
        )}
      />

      <Controller
        name="visibility"
        control={control}
        render={({ field }) => (
          <Stack gap={8}>
            <Label>Visibility</Label>
            <ResponsiveSelect
              value={field.value}
              onValueChange={field.onChange}
              placeholder="Select visibility"
              label="Visibility"
              testID="team-form-visibility"
              options={visibilityOptions.map((option) => ({
                value: option.value,
                label: option.label,
              }))}
            />
            {errors.visibility && (
              <Text
                style={{
                  color:
                    theme === "light" ? colors.error[700] : colors.error[300],
                }}
              >
                {errors.visibility.message}
              </Text>
            )}
          </Stack>
        )}
      />

      <Controller
        name="invitationPolicy"
        control={control}
        render={({ field }) => (
          <Stack gap={8}>
            <Label>Invitation Policy</Label>
            <ResponsiveSelect
              value={field.value}
              onValueChange={field.onChange}
              placeholder="Select invitation policy"
              label="Invitation Policy"
              testID="team-form-invitation-policy"
              options={invitationPolicyOptions.map((option) => ({
                value: option.value,
                label: option.label,
              }))}
            />
            {errors.invitationPolicy && (
              <Text
                style={{
                  color:
                    theme === "light" ? colors.error[700] : colors.error[300],
                }}
              >
                {errors.invitationPolicy.message}
              </Text>
            )}
          </Stack>
        )}
      />

      <Controller
        name="description"
        control={control}
        render={({ field }) => (
          <Stack gap={8}>
            <Label htmlFor="team-description">Description</Label>
            <TextArea
              id="team-description"
              testID="team-form-description"
              value={field.value ?? ""}
              onChangeText={(value) => field.onChange(value)}
              placeholder="Add context about this team"
              rows={4}
            />
            {errors.description && (
              <Text
                style={{
                  color:
                    theme === "light" ? colors.error[700] : colors.error[300],
                }}
              >
                {errors.description.message as string}
              </Text>
            )}
          </Stack>
        )}
      />

      <Controller
        name="defaultRoleId"
        control={control}
        render={({ field }) => (
          <Stack gap={8}>
            <Label>Default Role</Label>
            <ResponsiveSelect
              value={field.value ?? ""}
              onValueChange={(value) => {
                field.onChange(value);
                const role = roles.find((item) => item.id === value);
                if (role) {
                  setValue("defaultRoleKey", role.key, {
                    shouldValidate: true,
                  });
                }
              }}
              placeholder="Select default role"
              label="Default Role"
              testID="team-form-default-role"
              options={roles.map((role) => ({
                value: role.id,
                label: role.name,
              }))}
            />
            {errors.defaultRoleId && (
              <Text
                style={{
                  color:
                    theme === "light" ? colors.error[700] : colors.error[300],
                }}
              >
                {errors.defaultRoleId.message as string}
              </Text>
            )}
          </Stack>
        )}
      />

      <Row gap={8} justify="flex-end">
        <Button
          color="gray"
          variant="outline"
          onPress={onCancel ?? (() => router.back())}
          disabled={isSubmitting}
          testID="team-form-cancel"
        >
          Cancel
        </Button>
        <Button
          onPress={handleSubmit(onSubmit)}
          disabled={isSubmitting || !isDirty}
          testID="team-form-submit"
        >
          {isSubmitting
            ? "Saving…"
            : mode === "create"
            ? "Create Team"
            : "Save Changes"}
        </Button>
      </Row>
    </Stack>
  );

  if (isOptionsLoading && roles.length === 0) {
    return (
      <Stack flex={1} align="center" justify="center" padding="xl">
        <Spinner variant="ios" size="lg" />
        <Text style={{ marginTop: 16 }}>Loading team options…</Text>
      </Stack>
    );
  }

  return (
    <ScrollView
      style={{ flex: 1, backgroundColor: colors.bg[theme].subtle, padding: 24 }}
      showsVerticalScrollIndicator={false}
    >
      {renderContent()}
    </ScrollView>
  );
}
