import { Paragraph, Text, YStack } from 'tamagui'
import { AnchorHeading, StyleguidePage, useStyleguideContext } from './_components'

export default function AuditReportPage() {
  const { audit, unknowns } = useStyleguideContext()

  return (
    <StyleguidePage
      title="Audit Report"
      description="Machine-readable summary generated by the styleguide audit script."
    >
      <YStack gap="$6">
        <AnchorHeading description="Key tech stack and routing details from the audit JSON.">
          Summary
        </AnchorHeading>
        <YStack borderWidth={1} borderColor="$gray5" borderRadius="$6" padding="$4" gap="$2">
          <Text fontWeight="700">Framework</Text>
          <Paragraph color="$gray11">{audit.techStack.framework}</Paragraph>
          <Text fontWeight="700">Routing</Text>
          <Paragraph color="$gray11">{audit.routing.approach}</Paragraph>
          <Paragraph color="$gray11">Auth guard: {audit.routing.authGuard}</Paragraph>
        </YStack>

        <AnchorHeading description="Items that require more investigation.">
          Unknowns
        </AnchorHeading>
        <YStack gap="$3">
          {unknowns.map((item) => (
            <YStack key={item.item} borderWidth={1} borderColor="$gray5" borderRadius="$5" padding="$3">
              <Text fontWeight="700">{item.item}</Text>
              <Paragraph color="$gray11">{item.suggestion}</Paragraph>
            </YStack>
          ))}
        </YStack>
      </YStack>
    </StyleguidePage>
  )
}
