-- =========================================================
-- 012_seed-dogfood-tasks.sql
--
-- Phase 3 demo data: 3 punchlists + 14 tasks under the Unicorn org
-- — the dogfood-bugs + dogfood-ideas content that used to live in
-- docs/agents/DOGFOODING-{BUGS,IDEAS}.md before they were migrated
-- into the product by scripts/migrate-dogfood-md-to-tasks.ts.
--
-- Idempotent via ON CONFLICT (id) DO NOTHING.
-- =========================================================

BEGIN;

-- Punchlists
INSERT INTO core.punchlists (id, organization_id, name, description, status, created_by_user_id) SELECT '9a90e926-2063-4117-8627-c1a6033b4fd7'::uuid, o.id, 'Dogfood Bugs (Open)', 'Bugs surfaced by the dogfood loop, still open. Migrated from docs/agents/DOGFOODING-BUGS.md.', 'active', '00000000-0000-0000-0000-000000000002'::uuid FROM core.organizations o WHERE o.slug = 'unicorn' ON CONFLICT (id) DO NOTHING;
INSERT INTO core.punchlists (id, organization_id, name, description, status, created_by_user_id) SELECT '5b4f0f95-5c5f-4769-91bf-ee4314e12c71'::uuid, o.id, 'Dogfood Bugs (Fixed)', 'Bugs surfaced and fixed by the dogfood loop. Migrated from docs/agents/DOGFOODING-BUGS.md.', 'completed', '00000000-0000-0000-0000-000000000002'::uuid FROM core.organizations o WHERE o.slug = 'unicorn' ON CONFLICT (id) DO NOTHING;
INSERT INTO core.punchlists (id, organization_id, name, description, status, created_by_user_id) SELECT '35977e80-7bee-4bb8-a4ce-302ea06586de'::uuid, o.id, 'Dogfood Ideas', 'Feature ideas surfaced by the dogfood loop. Migrated from docs/agents/DOGFOODING-IDEAS.md.', 'active', '00000000-0000-0000-0000-000000000002'::uuid FROM core.organizations o WHERE o.slug = 'unicorn' ON CONFLICT (id) DO NOTHING;

-- Tasks (source: dogfooding-md)
INSERT INTO core.tasks (id, organization_id, punchlist_id, team_slug, title, description, status, priority, source, completed_at, created_by_user_id) SELECT 'daede8ed-bcb3-4a2a-ba27-d18af445ca9b'::uuid, o.id, '5b4f0f95-5c5f-4769-91bf-ee4314e12c71'::uuid, 'backend', '`POST /v1/work-logs` rejects all creates with `cannot insert a non-DEFAULT value into column "total_hours"`', '`packages/supabase/functions/api/routes/work-logs.ts:216` was inserting `total_hours: 0`, but `core.work_logs.total_hours` is a `GENERATED ... STORED` column derived from `time_entries`. Removed the explicit insert. Found while running the very first dogfood-log smoke test — exactly the kind of breakage the loop is meant to catch.', 'done', 'high', 'dogfooding-md', NULL, '00000000-0000-0000-0000-000000000002'::uuid FROM core.organizations o WHERE o.slug = 'unicorn' ON CONFLICT (id) DO NOTHING;
INSERT INTO core.tasks (id, organization_id, punchlist_id, team_slug, title, description, status, priority, source, completed_at, created_by_user_id) SELECT 'e01628b1-0290-49b4-add4-c5f2a961eea9'::uuid, o.id, '5b4f0f95-5c5f-4769-91bf-ee4314e12c71'::uuid, 'backend', '`POST /v1/work-logs` had three schema/SDK drift bugs that made any create impossible', '(a) `entryType` SDK enum is `single_day|date_range` but DB CHECK constraint requires `daily|project|task`; (b) `time_entries` items use `start_time`/`end_time` in SDK but DB `core.calculate_time_entries_total_hours()` reads `start`/`end`, silently computing `total_hours=0` and failing the `total_hours > 0` constraint; (c) `visibility=''organization''` SDK option fails the DB CHECK `visibility IN (''public'',''private'')`. Patched the API handler at `packages/supabase/functions/api/routes/work-logs.ts` to translate SDK shape → DB shape (single_day→daily, date_range→project, start_time→start, organization→private). Proper fix is a schema rename — see DOGFOODING-IDEAS.md.', 'done', 'high', 'dogfooding-md', NULL, '00000000-0000-0000-0000-000000000002'::uuid FROM core.organizations o WHERE o.slug = 'unicorn' ON CONFLICT (id) DO NOTHING;
INSERT INTO core.tasks (id, organization_id, punchlist_id, team_slug, title, description, status, priority, source, completed_at, created_by_user_id) SELECT '6178b0d5-a830-4697-8a3c-2b664d16dcc2'::uuid, o.id, '5b4f0f95-5c5f-4769-91bf-ee4314e12c71'::uuid, 'backend', '`work_logs_insert_self` RLS rejected valid user-JWT inserts (no end-user could create a log via the API)', 'root cause was that the `work_logs_select_self` SELECT policy delegated to `core.can_access_work_log(id)`, a SECURITY DEFINER function that recursively `SELECT EXISTS (... FROM core.work_logs ...)`. When called inside RETURNING evaluation, that function failed to see the just-inserted row, returning false and rejecting the row via the SELECT side-check. The error surfaced misleadingly as "row violates row-level security policy" pointing at the INSERT policy. Fix: inlined the access-check expression directly into the SELECT/UPDATE policies in `packages/supabase/migrations/324_work_logs_rls_inline_access_check.sql`. Verified end-to-end: PostgREST direct insert + SDK `client.workLogs.create()` both succeed with a user JWT. Dropped the service-role workaround in `scripts/dogfood-log.ts`.', 'done', 'high', 'dogfooding-md', NULL, '00000000-0000-0000-0000-000000000002'::uuid FROM core.organizations o WHERE o.slug = 'unicorn' ON CONFLICT (id) DO NOTHING;
INSERT INTO core.tasks (id, organization_id, punchlist_id, team_slug, title, description, status, priority, source, completed_at, created_by_user_id) SELECT 'b746ef54-b8aa-4a68-a755-718af8948f5b'::uuid, o.id, '5b4f0f95-5c5f-4769-91bf-ee4314e12c71'::uuid, 'backend', '`POST /v1/work-logs/:workLogId/submit` returned 404', 'SDK exposes `client.workLogs.submit()` but the API never implemented the endpoint. Added it to `packages/supabase/functions/api/routes/work-logs.ts`. Note: the SDK exposes ~15 other work-log methods (addCollaborator, addComment, uploadPhoto, getById, getOverview, getProjectOptions, getProjectRollup, deletePhoto, etc.) that are similarly unimplemented in the public API. Tracking the bigger gap in DOGFOODING-IDEAS.md rather than fixing all here.', 'done', 'high', 'dogfooding-md', NULL, '00000000-0000-0000-0000-000000000002'::uuid FROM core.organizations o WHERE o.slug = 'unicorn' ON CONFLICT (id) DO NOTHING;
INSERT INTO core.tasks (id, organization_id, punchlist_id, team_slug, title, description, status, priority, source, completed_at, created_by_user_id) SELECT '79ec884b-7a5b-409b-bb80-e1a799b3a0b2'::uuid, o.id, '5b4f0f95-5c5f-4769-91bf-ee4314e12c71'::uuid, 'backend', '`GET /v1/work-logs` silently ignored `statuses`, `search`, `sortField`, `sortDirection`, `dateFrom`, `dateTo` filters', 'the LIST handler at `packages/supabase/functions/api/routes/work-logs.ts` accepted only `page/pageSize/projectId/organizationId`. This meant the polished filters on the org Logs list UI (commit `460c28153`) couldn''t actually narrow results — every filter click returned the full 42-row list. Wired up all five filter params + sort, and verified status/search/sort all return the correctly-filtered counts. Found by phase2-seed verification.', 'done', 'high', 'dogfooding-md', NULL, '00000000-0000-0000-0000-000000000002'::uuid FROM core.organizations o WHERE o.slug = 'unicorn' ON CONFLICT (id) DO NOTHING;
INSERT INTO core.tasks (id, organization_id, punchlist_id, team_slug, title, description, status, priority, source, completed_at, created_by_user_id) SELECT '2683e96b-4af5-4284-b48e-eec15660119b'::uuid, o.id, '5b4f0f95-5c5f-4769-91bf-ee4314e12c71'::uuid, 'backend', '`GET /v1/work-logs/projects` (project picker for the create-log form) returned 404', 'endpoint was missing. Added it: returns construction_projects scoped to the caller''s orgs (or the explicit `organizationId` if the caller is a member), with `search` and `includeArchived` support, matching the SDK''s `ProjectOption` shape.', 'done', 'high', 'dogfooding-md', NULL, '00000000-0000-0000-0000-000000000002'::uuid FROM core.organizations o WHERE o.slug = 'unicorn' ON CONFLICT (id) DO NOTHING;
INSERT INTO core.tasks (id, organization_id, punchlist_id, team_slug, title, description, status, priority, source, completed_at, created_by_user_id) SELECT 'cd863a63-7005-455a-875f-c7e6c1b5817f'::uuid, o.id, '5b4f0f95-5c5f-4769-91bf-ee4314e12c71'::uuid, 'backend', '`GET /v1/work-logs/:workLogId` (the detail page) returned 404', 'endpoint was missing. Added it with two visibility paths: RLS-scoped first (own + collaborator), then a service-role fallback that checks the caller is a member of the log''s owning org (so admins can see all org members'' logs, mirroring the LIST handler).', 'done', 'high', 'dogfooding-md', NULL, '00000000-0000-0000-0000-000000000002'::uuid FROM core.organizations o WHERE o.slug = 'unicorn' ON CONFLICT (id) DO NOTHING;
INSERT INTO core.tasks (id, organization_id, punchlist_id, team_slug, title, description, status, priority, source, completed_at, created_by_user_id) SELECT '9f84313d-5fbe-4891-bd1d-cb1b51e2879e'::uuid, o.id, '35977e80-7bee-4bb8-a4ce-302ea06586de'::uuid, NULL, 'Add `team_id` to `core.work_logs`', 'work_logs currently has no team association, so the dogfood script puts `[team:slug]` in the description as a workaround. Filtering/grouping by team in the Logs UI needs first-class support. — source: scripts/dogfood-log.ts', 'todo', 'medium', 'dogfooding-md', NULL, '00000000-0000-0000-0000-000000000002'::uuid FROM core.organizations o WHERE o.slug = 'unicorn' ON CONFLICT (id) DO NOTHING;
INSERT INTO core.tasks (id, organization_id, punchlist_id, team_slug, title, description, status, priority, source, completed_at, created_by_user_id) SELECT '17b2f02c-b685-4305-99a4-9d6a41b31260'::uuid, o.id, '35977e80-7bee-4bb8-a4ce-302ea06586de'::uuid, NULL, 'Rename `core.construction_projects` → `core.projects` with `kind` discriminator', 'repurposing the construction projects table for software work is a schema misnomer flagged in Phase 0. — source: packages/supabase/seeds/011_seed-real-org-structure.sql', 'todo', 'medium', 'dogfooding-md', NULL, '00000000-0000-0000-0000-000000000002'::uuid FROM core.organizations o WHERE o.slug = 'unicorn' ON CONFLICT (id) DO NOTHING;
INSERT INTO core.tasks (id, organization_id, punchlist_id, team_slug, title, description, status, priority, source, completed_at, created_by_user_id) SELECT 'ae9bb5d7-83f0-4ef5-b594-79b42db034bb'::uuid, o.id, '35977e80-7bee-4bb8-a4ce-302ea06586de'::uuid, NULL, 'Admin UI for API keys', 'production dogfood logging needs a service API key, but there''s no admin UI today (only manual provisioning). — source: Phase 4 plan', 'todo', 'medium', 'dogfooding-md', NULL, '00000000-0000-0000-0000-000000000002'::uuid FROM core.organizations o WHERE o.slug = 'unicorn' ON CONFLICT (id) DO NOTHING;
INSERT INTO core.tasks (id, organization_id, punchlist_id, team_slug, title, description, status, priority, source, completed_at, created_by_user_id) SELECT 'a7f7a9ee-98b7-4dd9-83d4-c15f72964d8f'::uuid, o.id, '35977e80-7bee-4bb8-a4ce-302ea06586de'::uuid, NULL, 'Rename `core.work_logs` → `core.logs` and `client.workLogs` → `client.logs`', 'UI already says "Logs"; back end is the lag. Larger blast radius, defer until dogfood loop is stable. — source: Phase 3 plan', 'todo', 'medium', 'dogfooding-md', NULL, '00000000-0000-0000-0000-000000000002'::uuid FROM core.organizations o WHERE o.slug = 'unicorn' ON CONFLICT (id) DO NOTHING;
INSERT INTO core.tasks (id, organization_id, punchlist_id, team_slug, title, description, status, priority, source, completed_at, created_by_user_id) SELECT 'fe8714f4-c0e2-4cfb-a7e8-bf6bd3bda0d7'::uuid, o.id, '35977e80-7bee-4bb8-a4ce-302ea06586de'::uuid, NULL, 'Realign SDK / DB work-log schemas', 'the SDK exposes a richer model (`entryType: single_day|date_range`, `time_entries: {start_time,end_time}`, `visibility: private|organization|public`) than the DB CHECK constraints allow (`daily|project|task`, `{start,end}`, `public|private`). The API handler currently bridges with a translation shim — proper fix is to migrate the DB schema to match the SDK (or vice versa) and drop the shim. — source: 2026-05-18 dogfood smoke test (see DOGFOODING-BUGS.md)', 'todo', 'medium', 'dogfooding-md', NULL, '00000000-0000-0000-0000-000000000002'::uuid FROM core.organizations o WHERE o.slug = 'unicorn' ON CONFLICT (id) DO NOTHING;
INSERT INTO core.tasks (id, organization_id, punchlist_id, team_slug, title, description, status, priority, source, completed_at, created_by_user_id) SELECT '315395fc-1497-44b6-ac11-8232e69f3588'::uuid, o.id, '35977e80-7bee-4bb8-a4ce-302ea06586de'::uuid, NULL, 'Wire up missing public-API endpoints for work logs', 'SDK at `packages/sdk/src/resources/work-logs.ts` exposes ~15 methods (getById, getOverview, getProjectOptions, getProjectRollup, addCollaborator, updateCollaborator, addComment, uploadPhoto, updatePhotoMetadata, updatePhotoVisibility, deletePhoto, moveToProject, approveMoveRequest, denyMoveRequest, exportWorkLog) that the API at `packages/supabase/functions/api/routes/work-logs.ts` does not implement. Submit was added on 2026-05-18 to unblock dogfood; the rest still 404. Implementing these one-by-one as we hit them in the dogfood loop is a great unit-of-work for future sessions. — source: 2026-05-18 dogfood smoke test (see DOGFOODING-BUGS.md)', 'todo', 'medium', 'dogfooding-md', NULL, '00000000-0000-0000-0000-000000000002'::uuid FROM core.organizations o WHERE o.slug = 'unicorn' ON CONFLICT (id) DO NOTHING;
INSERT INTO core.tasks (id, organization_id, punchlist_id, team_slug, title, description, status, priority, source, completed_at, created_by_user_id) SELECT '66407a2d-16b0-47c0-8347-47a5cf8f23bb'::uuid, o.id, '35977e80-7bee-4bb8-a4ce-302ea06586de'::uuid, NULL, 'Build first-class Tasks + Punchlists', 'schema, RLS, and CRUD API landed in migration `325_tasks_and_punchlists.sql` and `packages/supabase/functions/api/routes/{tasks,punchlists}.ts`. Tasks link to work logs via `core.work_log_tasks`. SDK + UI follow in Phase 3.2.', 'done', 'medium', 'dogfooding-md', NULL, '00000000-0000-0000-0000-000000000002'::uuid FROM core.organizations o WHERE o.slug = 'unicorn' ON CONFLICT (id) DO NOTHING;

COMMIT;
