-- =========================================================
-- Jobs Seed Data
-- Comprehensive job postings with full ATS metadata
-- =========================================================

BEGIN;

-- Insert jobs with comprehensive metadata
WITH org_lookup AS (
  SELECT id, slug FROM public.organizations
)
INSERT INTO public.jobs (
  slug,
  organization_id,
  title,
  description,
  status,
  employment_type,
  remote_option,
  position_level,
  location,
  address,
  pay_range_min_cents,
  pay_range_max_cents,
  pay_range_type,
  posted_at,
  closes_at,
  require_current_location,
  require_relocation_willingness,
  minimum_years_experience,
  require_work_authorization,
  require_earliest_start_date,
  enable_auto_reject,
  auto_reject_criteria,
  minimum_score,
  internal_job_code,
  department,
  cost_center,
  number_of_openings,
  priority_level,
  requisition_number,
  job_category,
  is_confidential,
  application_deadline,
  target_start_date,
  estimated_hire_date,
  minimum_education_level,
  require_background_check,
  background_check_type,
  require_drug_test,
  require_drivers_license,
  drivers_license_type,
  language_requirements,
  physical_requirements,
  travel_percentage,
  shift_requirements,
  benefits_summary,
  has_bonus_structure,
  bonus_details,
  sign_on_bonus_cents,
  has_relocation_package,
  relocation_package_details,
  overtime_eligible,
  pay_frequency,
  custom_application_questions,
  required_attachments,
  estimated_application_time_minutes,
  application_expiry_days,
  work_locations,
  relocation_assistance_offered,
  relocation_assistance_details,
  work_schedule_details,
  timezone,
  posting_channels,
  is_featured,
  featured_until,
  seo_keywords,
  eeo_job_category,
  is_veteran_friendly,
  is_disability_friendly,
  source_tracking_enabled,
  utm_parameters
)
SELECT
  data.slug,
  ol.id,
  data.title,
  data.description,
  data.status,
  data.employment_type,
  data.remote_option,
  data.position_level,
  data.location,
  data.address,
  data.pay_range_min_cents,
  data.pay_range_max_cents,
  data.pay_range_type,
  data.posted_at,
  data.closes_at,
  data.require_current_location,
  data.require_relocation_willingness,
  data.minimum_years_experience,
  data.require_work_authorization,
  data.require_earliest_start_date,
  data.enable_auto_reject,
  data.auto_reject_criteria,
  data.minimum_score,
  data.internal_job_code,
  data.department,
  data.cost_center,
  data.number_of_openings,
  data.priority_level,
  data.requisition_number,
  data.job_category,
  data.is_confidential,
  data.application_deadline,
  data.target_start_date,
  data.estimated_hire_date,
  data.minimum_education_level,
  data.require_background_check,
  data.background_check_type,
  data.require_drug_test,
  data.require_drivers_license,
  data.drivers_license_type,
  data.language_requirements,
  data.physical_requirements,
  data.travel_percentage,
  data.shift_requirements,
  data.benefits_summary,
  data.has_bonus_structure,
  data.bonus_details,
  data.sign_on_bonus_cents,
  data.has_relocation_package,
  data.relocation_package_details,
  data.overtime_eligible,
  data.pay_frequency,
  data.custom_application_questions,
  data.required_attachments,
  data.estimated_application_time_minutes,
  data.application_expiry_days,
  data.work_locations,
  data.relocation_assistance_offered,
  data.relocation_assistance_details,
  data.work_schedule_details,
  data.timezone,
  data.posting_channels,
  data.is_featured,
  data.featured_until,
  data.seo_keywords,
  data.eeo_job_category,
  data.is_veteran_friendly,
  data.is_disability_friendly,
  data.source_tracking_enabled,
  data.utm_parameters
FROM (VALUES
  -- Job 1: Senior Project Manager
  (
    'senior-project-manager-construction'::text,
    'midland-construction'::citext,
    'Senior Project Manager'::text,
    E'Lead large-scale commercial construction projects. Manage budgets exceeding $10M, coordinate multiple teams, ensure OSHA compliance.\n\nKey Responsibilities:\n• Oversee planning, scheduling, and execution\n• Manage project budgets and P&L\n• Coordinate subcontractors and suppliers\n• Ensure safety and building code compliance\n• Client and stakeholder interface\n\nQualifications:\n• 10+ years commercial construction PM experience\n• Deep knowledge of building codes and methods\n• Proven on-time, on-budget delivery\n• Strong leadership and communication skills\n• Experience with Procore or similar PM software'::text,
    'open'::text,
    'full_time'::text,
    'on_site'::text,
    'Senior / Lead'::text,
    'Midland, MI'::text,
    jsonb_build_object('street', '2500 Industrial Blvd', 'city', 'Midland', 'state', 'MI', 'zip', '48640', 'country', 'USA', 'latitude', 43.6156, 'longitude', -84.2472),
    9500000, 14000000, 'salary'::text,
    now() - interval '7 days', now() + interval '60 days',
    true, true, 10, true, true,
    true, jsonb_build_object('score_minimum', 70, 'require_work_authorization', true), 75,
    'PROJ-2025-001'::text, 'Project Management'::text, 'CC-PM-001'::text, 1, 'high'::text, 'REQ-PM-2025-Q1-001'::text, 'Construction Management'::text, false,
    (now() + interval '30 days')::timestamptz, (now() + interval '60 days')::date, (now() + interval '75 days')::date,
    'bachelor'::text, true, 'Standard background check including criminal history and employment verification'::text, false, true, 'Class D'::text,
    jsonb_build_array(jsonb_build_object('language', 'English', 'proficiency', 'fluent')),
    jsonb_build_object('lifting', 'Occasional lifting up to 25 lbs', 'standing', 'Extended periods on construction sites'),
    10, 'Standard business hours with occasional evening/weekend site visits'::text,
    E'Comprehensive benefits:\n• Medical, Dental, Vision (90% employer paid)\n• 401(k) with 5% match\n• 3 weeks PTO + 10 holidays\n• Professional development budget'::text,
    true, 'Annual bonus up to 20% based on project delivery'::text, 1000000, true, 'Full relocation package available'::text, false, 'semimonthly'::text,
    jsonb_build_array(jsonb_build_object('id', gen_random_uuid()::text, 'question', 'Describe your largest project managed', 'type', 'long_text', 'required', true)),
    jsonb_build_object('resume', jsonb_build_object('required', true, 'max_size_mb', 5), 'cover_letter', jsonb_build_object('required', true, 'max_size_mb', 2)),
    25, 90,
    jsonb_build_array(jsonb_build_object('address', jsonb_build_object('city', 'Midland', 'state', 'MI'), 'is_primary', true, 'percentage_time', 100)),
    true, 'Full relocation assistance available'::text, 'Monday-Friday, 7:00 AM - 4:00 PM'::text, 'America/Detroit'::text,
    jsonb_build_object('internal_only', false, 'external_boards', jsonb_build_array('Indeed', 'LinkedIn'), 'referral_bonus_enabled', true, 'referral_bonus_cents', 300000),
    true, (now() + interval '30 days')::timestamptz, ARRAY['construction', 'project manager', 'midland', 'michigan'],
    '1.1 - Executive/Senior Level Officials and Managers'::text, true, true, true,
    jsonb_build_object('utm_source', 'careers_page', 'utm_campaign', 'q1_2025_hiring')
  ),
  
  -- Job 2: Heavy Equipment Operator
  (
    'heavy-equipment-operator-manufacturing'::text,
    'bay-city-manufacturing'::citext,
    'Heavy Equipment Operator'::text,
    E'Operate forklifts, reach trucks, and order pickers. Full-time position with excellent benefits.\n\nResponsibilities:\n• Operate equipment safely and efficiently\n• Load/unload materials\n• Maintain inventory records\n• Follow safety protocols\n\nRequirements:\n• Forklift certification (training available)\n• 2+ years equipment operation experience\n• Lift up to 50 lbs regularly\n• Basic computer skills'::text,
    'open'::text,
    'full_time'::text,
    'on_site'::text,
    'Entry Level / Junior'::text,
    'Bay City, MI'::text,
    jsonb_build_object('street', '3200 Manufacturing Drive', 'city', 'Bay City', 'state', 'MI', 'zip', '48706', 'country', 'USA', 'latitude', 43.5945, 'longitude', -83.8889),
    2100000, 2750000, 'hourly'::text,
    now() - interval '3 days', now() + interval '45 days',
    true, false, 2, true, true,
    true, jsonb_build_object('score_minimum', 60, 'require_work_authorization', true), 65,
    'MFG-EQP-2025-003'::text, 'Operations'::text, 'CC-OPS-002'::text, 3, 'normal'::text, 'REQ-OPS-2025-001'::text, 'Equipment Operations'::text, false,
    (now() + interval '20 days')::timestamptz, (now() + interval '30 days')::date, (now() + interval '37 days')::date,
    'high_school'::text, true, 'Criminal background check'::text, true, false, NULL::text,
    jsonb_build_array(jsonb_build_object('language', 'English', 'proficiency', 'conversational')),
    jsonb_build_object('lifting', 'Frequently lift up to 50 lbs', 'standing', 'Standing for entire shift'),
    0, '2nd shift: 3:00 PM - 11:30 PM Monday-Friday'::text,
    E'Benefits starting day one:\n• Health insurance (80% employer paid)\n• 401(k) with 4% match\n• 2 weeks PTO\n• 6 paid holidays'::text,
    true, 'Quarterly bonuses up to $500'::text, NULL::int, false, NULL::text, true, 'biweekly'::text,
    jsonb_build_array(jsonb_build_object('id', gen_random_uuid()::text, 'question', 'Do you have forklift certification?', 'type', 'yes_no', 'required', true)),
    jsonb_build_object('resume', jsonb_build_object('required', true, 'max_size_mb', 5)),
    15, 60,
    jsonb_build_array(jsonb_build_object('address', jsonb_build_object('city', 'Bay City', 'state', 'MI'), 'is_primary', true, 'percentage_time', 100)),
    false, NULL::text, 'Second shift: 3:00 PM - 11:30 PM'::text, 'America/Detroit'::text,
    jsonb_build_object('internal_only', false, 'external_boards', jsonb_build_array('Indeed', 'ZipRecruiter'), 'referral_bonus_enabled', true, 'referral_bonus_cents', 100000),
    false, NULL::timestamptz, ARRAY['forklift', 'warehouse', 'manufacturing', 'bay city'],
    '6 - Craft Workers'::text, true, true, true,
    jsonb_build_object('utm_source', 'careers_page', 'utm_campaign', 'operations_hiring_2025')
  ),

  -- Job 3: CDL-A Truck Driver
  (
    'cdl-a-truck-driver-regional'::text,
    'saginaw-transportation'::citext,
    'CDL-A Truck Driver - Regional Routes'::text,
    E'Regional CDL-A driver position. Home every weekend, excellent pay, modern equipment.\n\nHighlights:\n• Home every weekend guaranteed\n• Newer fleet (2-3 years old)\n• 2,200-2,500 avg weekly miles\n• Weekly direct deposit\n• No-touch freight\n\nRoutes:\n• Regional: MI, OH, IN, IL\n• Monday-Friday schedules\n• Mostly drop and hook\n\nRequirements:\n• Valid Class A CDL\n• 1+ year OTR experience\n• Clean MVR\n• Pass DOT physical\n• 23+ years old'::text,
    'open'::text,
    'full_time'::text,
    'remote'::text,
    'Mid Level / Intermediate'::text,
    'Regional - Midwest'::text,
    jsonb_build_object('street', '1000 Transportation Blvd', 'city', 'Saginaw', 'state', 'MI', 'zip', '48601', 'country', 'USA', 'latitude', 43.4195, 'longitude', -83.9508),
    5500000, 7500000, 'salary'::text,
    now() - interval '14 days', now() + interval '90 days',
    false, false, 1, true, true,
    true, jsonb_build_object('score_minimum', 55, 'require_work_authorization', true), 60,
    'TRANS-CDL-2025-008'::text, 'Transportation'::text, 'CC-TRANS-001'::text, 5, 'urgent'::text, 'REQ-CDL-2025-Q1-002'::text, 'Commercial Driving'::text, false,
    (now() + interval '45 days')::timestamptz, (now() + interval '60 days')::date, (now() + interval '67 days')::date,
    'high_school'::text, true, 'DOT background check including MVR'::text, true, true, 'CDL-A'::text,
    jsonb_build_array(jsonb_build_object('language', 'English', 'proficiency', 'fluent')),
    jsonb_build_object('lifting', 'Occasional lifting up to 75 lbs', 'sitting', 'Extended periods sitting'),
    0, 'Regional routes with predictable schedules'::text,
    E'Industry-leading compensation:\n• $0.55-$0.62 per mile\n• Weekly direct deposit\n• Medical, Dental, Vision (75% employer paid)\n• 401(k) with match\n• Per diem and detention pay'::text,
    true, 'Safety bonus quarterly up to $400'::text, NULL::int, false, NULL::text, true, 'weekly'::text,
    jsonb_build_array(jsonb_build_object('id', gen_random_uuid()::text, 'question', 'Years of OTR CDL-A experience?', 'type', 'single_choice', 'required', true, 'options', jsonb_build_array('Less than 1', '1-2 years', '3-5 years', '5+ years'))),
    jsonb_build_object('cdl_license', jsonb_build_object('required', true, 'max_size_mb', 2)),
    20, 45,
    jsonb_build_array(jsonb_build_object('address', jsonb_build_object('city', 'Saginaw', 'state', 'MI'), 'is_primary', true, 'percentage_time', 100)),
    false, NULL::text, 'Regional routes, home every weekend'::text, 'America/Detroit'::text,
    jsonb_build_object('internal_only', false, 'external_boards', jsonb_build_array('Indeed', 'CDLJobs'), 'referral_bonus_enabled', true, 'referral_bonus_cents', 150000),
    true, (now() + interval '30 days')::timestamptz, ARRAY['cdl-a', 'truck driver', 'regional', 'midwest'],
    '9 - Transportation and Material Moving Workers'::text, true, true, true,
    jsonb_build_object('utm_source', 'careers_page', 'utm_campaign', 'driver_shortage_2025')
  ),

  -- Job 4: Electrical Technician
  (
    'electrical-technician-renewable-energy'::text,
    'mount-pleasant-energy'::citext,
    'Electrical Technician - Renewable Energy'::text,
    E'Skilled Electrical Technician for renewable energy projects. Work on solar and wind installations across Michigan.\n\nDuties:\n• Install and maintain solar/wind systems\n• Read electrical schematics\n• Perform preventive maintenance\n• Work with high-voltage systems safely\n• Document work and maintain records\n• Travel to project sites (vehicle provided)\n\nQualifications:\n• Journeyman Electrician license required\n• 5+ years commercial/industrial experience\n• Renewable energy experience preferred\n• Strong troubleshooting skills\n• Comfortable working at heights'::text,
    'open'::text,
    'contract'::text,
    'on_site'::text,
    'Mid Level / Intermediate'::text,
    'Mount Pleasant, MI'::text,
    jsonb_build_object('street', '800 Energy Parkway', 'city', 'Mount Pleasant', 'state', 'MI', 'zip', '48858', 'country', 'USA', 'latitude', 43.5978, 'longitude', -84.7675),
    3500000, 4800000, 'hourly'::text,
    now() - interval '5 days', now() + interval '30 days',
    true, false, 5, true, true,
    true, jsonb_build_object('score_minimum', 70, 'require_work_authorization', true), 75,
    'ENRG-ELEC-2025-005'::text, 'Field Operations'::text, 'CC-FIELD-003'::text, 2, 'high'::text, 'REQ-ELEC-2025-001'::text, 'Electrical Trades'::text, false,
    (now() + interval '15 days')::timestamptz, (now() + interval '25 days')::date, (now() + interval '32 days')::date,
    'associate'::text, true, 'Criminal background check and drug screen'::text, true, true, 'Class D'::text,
    jsonb_build_array(jsonb_build_object('language', 'English', 'proficiency', 'fluent')),
    jsonb_build_object('lifting', 'Lift up to 75 lbs', 'climbing', 'Frequent climbing ladders', 'heights', 'Work at heights regularly'),
    30, 'Monday-Friday, some weekend/evening work during installations'::text,
    E'Competitive benefits:\n• Health, Dental, Vision insurance\n• 401(k) retirement plan\n• Company vehicle and fuel card\n• Latest tools provided\n• Ongoing training on new tech'::text,
    true, 'Performance bonuses based on project completion'::text, NULL::int, false, NULL::text, true, 'biweekly'::text,
    jsonb_build_array(jsonb_build_object('id', gen_random_uuid()::text, 'question', 'Do you have Journeyman Electrician license?', 'type', 'yes_no', 'required', true)),
    jsonb_build_object('resume', jsonb_build_object('required', true, 'max_size_mb', 5), 'licenses', jsonb_build_object('required', true, 'max_size_mb', 5)),
    20, 30,
    jsonb_build_array(jsonb_build_object('address', jsonb_build_object('city', 'Mount Pleasant', 'state', 'MI'), 'is_primary', true, 'percentage_time', 100)),
    false, NULL::text, 'Monday-Friday, travel to project sites'::text, 'America/Detroit'::text,
    jsonb_build_object('internal_only', false, 'external_boards', jsonb_build_array('Indeed', 'GlassDoor'), 'referral_bonus_enabled', true, 'referral_bonus_cents', 200000),
    false, NULL::timestamptz, ARRAY['electrician', 'renewable energy', 'solar', 'wind', 'michigan'],
    '6 - Craft Workers'::text, true, true, true,
    jsonb_build_object('utm_source', 'careers_page', 'utm_campaign', 'renewable_energy_2025')
  )
) AS data(
  slug, org_slug, title, description, status, employment_type, remote_option, position_level, location, address,
  pay_range_min_cents, pay_range_max_cents, pay_range_type, posted_at, closes_at,
  require_current_location, require_relocation_willingness, minimum_years_experience, require_work_authorization, require_earliest_start_date,
  enable_auto_reject, auto_reject_criteria, minimum_score,
  internal_job_code, department, cost_center, number_of_openings, priority_level, requisition_number, job_category, is_confidential, application_deadline, target_start_date, estimated_hire_date,
  minimum_education_level, require_background_check, background_check_type, require_drug_test, require_drivers_license, drivers_license_type,
  language_requirements, physical_requirements, travel_percentage, shift_requirements,
  benefits_summary, has_bonus_structure, bonus_details, sign_on_bonus_cents, has_relocation_package, relocation_package_details, overtime_eligible, pay_frequency,
  custom_application_questions, required_attachments, estimated_application_time_minutes, application_expiry_days,
  work_locations, relocation_assistance_offered, relocation_assistance_details, work_schedule_details, timezone,
  posting_channels, is_featured, featured_until, seo_keywords,
  eeo_job_category, is_veteran_friendly, is_disability_friendly, source_tracking_enabled, utm_parameters
)
JOIN org_lookup ol ON ol.slug = data.org_slug
ON CONFLICT (slug) DO NOTHING;

COMMIT;
