import { OpenAPIHono } from "@hono/zod-openapi";
import type { ApiEnv } from "./middleware/auth.ts";

const app = new OpenAPIHono<ApiEnv>();

/**
 * OpenAPI Documentation
 *
 * Provides machine-readable API specification for third-party developers
 * Supports Swagger UI and other OpenAPI tools
 *
 * Note: Individual route documentation is generated by each router.
 * This file provides the central Swagger UI and consolidated spec.
 */
app.doc("/openapi.json", {
  openapi: "3.1.0",
  info: {
    title: "Scaffald Public API",
    version: "1.0.0",
    description: `
# Scaffald Public API

Public REST API for third-party integrations, built with Hono framework on Deno.

## Architecture

**Hybrid Approach**: This REST API coexists with the existing tRPC API:
- **REST**: Public-facing endpoints for third-party integrations (this API)
- **tRPC**: Internal admin tools and mobile app (separate service)

## Authentication

All endpoints use Bearer token authentication with Supabase JWT tokens:

\`\`\`bash
curl -H "Authorization: Bearer YOUR_JWT_TOKEN" \\
  https://your-project.supabase.co/functions/v1/api/v1/jobs
\`\`\`

OAuth integration endpoints are protected by OAuth 2.0 with PKCE.

## Rate Limiting

Public API endpoints are rate-limited:
- **Free tier**: 100 requests per 15 minutes
- **Paid tier**: Higher limits based on plan

## Response Format

All successful responses follow this format:
\`\`\`json
{
  "data": { /* response data */ },
  "pagination": { /* optional pagination metadata */ }
}
\`\`\`

Error responses follow this format:
\`\`\`json
{
  "error": "Error message"
}
\`\`\`
    `,
    contact: {
      name: "API Support",
      email: "api@scaffald.com",
    },
    license: {
      name: "Proprietary",
    },
  },
  servers: [
    {
      url: Deno.env.get("SUPABASE_URL")
        ? `${Deno.env.get("SUPABASE_URL")}/functions/v1/api`
        : "https://your-project.supabase.co/functions/v1/api",
      description: "Production API",
    },
  ],
  tags: [
    { name: "Jobs", description: "Job listing and search endpoints" },
    {
      name: "Applications",
      description: "Job application management (Week 3)",
    },
    { name: "Profiles", description: "Public profile discovery (Week 4)" },
    { name: "OAuth", description: "OAuth 2.0 authorization server" },
    { name: "Health", description: "API health and status checks" },
  ],
});

// Swagger UI endpoint
app.get("/", (c) => {
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Scaffald API Documentation</title>
  <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css" />
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
  <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-standalone-preset.js"></script>
  <script>
    window.onload = function() {
      const ui = SwaggerUIBundle({
        url: '/openapi.json',
        dom_id: '#swagger-ui',
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        layout: "StandaloneLayout"
      })
    }
  </script>
</body>
</html>
  `;
  return c.html(html);
});

export default app;
