// @ts-nocheck

import { AnchorHeading, ExampleCard, StyleguidePage } from '@app/styleguide'
import { Breadcrumb, Text, useBreadcrumbs, XStack, YStack } from '@app/ui'
import { ChevronRight } from '@tamagui/lucide-icons'
import { Fragment } from 'react'

const trail = ['Home', 'Teams', 'Compliance', 'Training']

export default function BreadcrumbsPage() {
  return (
    <StyleguidePage
      title="Breadcrumbs"
      description="Hierarchy trails with responsive truncation and automatic route-based generation."
    >
      <YStack gap="$6">
        <AnchorHeading
          id="breadcrumbs-basic"
          title="Basic breadcrumb component"
          description="Simple breadcrumb trail with clickable navigation links and terminal item as plain text."
        />
        <ExampleCard
          title="Basic usage"
          description="Simple breadcrumb with clickable links and terminal item."
          code={`<Breadcrumb
  items={[
    { label: 'Dashboard', href: '/dashboard' },
    { label: 'Discover', href: '/dashboard/discover' },
    { label: 'Workers', isActive: true },
  ]}
/>`}
        >
          <Breadcrumb
            items={[
              { label: 'Dashboard', href: '/dashboard' },
              { label: 'Discover', href: '/dashboard/discover' },
              { label: 'Workers', isActive: true },
            ]}
          />
        </ExampleCard>

        <AnchorHeading
          id="breadcrumbs-legacy"
          title="Legacy pattern (deprecated)"
          description="Original Bootstrap-style breadcrumbs using XStack - kept for reference."
        />
        <ExampleCard
          title="Trail"
          description="Simple crumb trail with chevron icons."
          code={`<XStack alignItems="center">
  {trail.map((item, index) => (
    <Fragment key={item}>
      <Text>{item}</Text>
      {index < trail.length - 1 ? <ChevronRight size={14} /> : null}
    </Fragment>
  ))}
</XStack>`}
        >
          <BreadcrumbTrail items={trail} />
        </ExampleCard>

        <AnchorHeading
          id="breadcrumbs-collapsed"
          title="Collapsed breadcrumbs"
          description="Deep hierarchies automatically collapse on desktop and mobile with ellipsis dropdown."
        />
        <ExampleCard
          title="Desktop collapse (4+ tiers)"
          description="On desktop, breadcrumbs collapse after 4 tiers showing first and last items with ellipsis."
          code={`<Breadcrumb
  items={[
    { label: 'Dashboard', href: '/dashboard' },
    { label: 'Profile', href: '/dashboard/profile' },
    { label: 'Experience', href: '/dashboard/profile/experience' },
    { label: 'Work History', href: '/dashboard/profile/experience/work' },
    { label: 'Edit', isActive: true },
  ]}
  maxItemsDesktop={4}
/>`}
        >
          <Breadcrumb
            items={[
              { label: 'Dashboard', href: '/dashboard' },
              { label: 'Profile', href: '/dashboard/profile' },
              { label: 'Experience', href: '/dashboard/profile/experience' },
              { label: 'Work History', href: '/dashboard/profile/experience/work' },
              { label: 'Edit', isActive: true },
            ]}
            maxItemsDesktop={4}
          />
        </ExampleCard>

        <ExampleCard
          title="Mobile collapse (2+ tiers)"
          description="On mobile, only the last 2 tiers are shown with ellipsis for hidden items."
          code={`<Breadcrumb
  items={[
    { label: 'Dashboard', href: '/dashboard' },
    { label: 'Profile', href: '/dashboard/profile' },
    { label: 'Experience', href: '/dashboard/profile/experience' },
    { label: 'Edit', isActive: true },
  ]}
  maxItemsMobile={2}
/>`}
        >
          <Breadcrumb
            items={[
              { label: 'Dashboard', href: '/dashboard' },
              { label: 'Profile', href: '/dashboard/profile' },
              { label: 'Experience', href: '/dashboard/profile/experience' },
              { label: 'Edit', isActive: true },
            ]}
            maxItemsMobile={2}
          />
        </ExampleCard>

        <AnchorHeading
          id="breadcrumbs-auto-generation"
          title="Auto-generation from routes"
          description="Automatically generate breadcrumbs from the current route using the useBreadcrumbs hook."
        />
        <ExampleCard
          title="Auto-generated breadcrumbs"
          description="Breadcrumbs automatically generated from the current route path."
          code={`import { useBreadcrumbs } from '@app/ui';

const { breadcrumbs } = useBreadcrumbs({ autoGenerate: true });
<Breadcrumb items={breadcrumbs} />`}
        >
          <AutoGeneratedExample />
        </ExampleCard>

        <AnchorHeading
          id="breadcrumbs-custom"
          title="Custom navigation"
          description="Use the onItemPress callback for custom navigation logic."
        />
        <ExampleCard
          title="Custom item press handler"
          description="Handle breadcrumb clicks with custom logic instead of default navigation."
          code={`<Breadcrumb
  items={[
    { label: 'Dashboard', href: '/dashboard' },
    { label: 'Profile', href: '/dashboard/profile' },
    { label: 'Settings', isActive: true },
  ]}
  onItemPress={(item, index) => {
    console.log('Clicked:', item.label, 'at index', index);
    // Custom navigation logic
  }}
/>`}
        >
          <Breadcrumb
            items={[
              { label: 'Dashboard', href: '/dashboard' },
              { label: 'Profile', href: '/dashboard/profile' },
              { label: 'Settings', isActive: true },
            ]}
            onItemPress={(_item, _index) => {
              // Custom handler - in real usage, you'd navigate here
              // Example: router.push(_item.href || '/')
            }}
          />
        </ExampleCard>
      </YStack>
    </StyleguidePage>
  )
}

function AutoGeneratedExample() {
  const { breadcrumbs } = useBreadcrumbs({ autoGenerate: true })
  return <Breadcrumb items={breadcrumbs} />
}

type BreadcrumbTrailProps = {
  items: string[]
}

const BreadcrumbTrail = ({ items }: BreadcrumbTrailProps) => (
  <XStack alignItems="center" gap="$2" flexWrap="wrap">
    {items.map((item, index) => (
      <Fragment key={item}>
        <Text fontSize={12} color={index === items.length - 1 ? '$color11' : '$color10'}>
          {item}
        </Text>
        {index < items.length - 1 ? <ChevronRight size={12} color="var(--color8)" /> : null}
      </Fragment>
    ))}
  </XStack>
)
