import { useEffect, useMemo, useState } from 'react'
import { Controller, useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { useRouter } from 'expo-router'
import {
  Button,
  Input,
  Label,
  ScrollView,
  Select,
  Spinner,
  Text,
  TextArea,
  XStack,
  YStack,
} from 'tamagui'
import { Check, ChevronDown } from '@tamagui/lucide-icons'
import { useToastController } from '@tamagui/toast'
import type { z } from 'zod'

import {
  teamCreateBaseSchema,
  teamCreateSchema,
  type TeamCreateInput,
  teamRoleKeySchema,
  TEAM_INVITATION_POLICIES,
  TEAM_VISIBILITIES,
} from '@app/schemas'
import { ROUTES } from '@app/core/constants/routes'
import { api } from '@app/core/utils/api'

import { useTeamFormOptions } from '../hooks/useTeamFormOptions'

type TeamVisibility = (typeof TEAM_VISIBILITIES)[number]
type TeamRoleKey = z.infer<typeof teamRoleKeySchema>
type TeamInvitationPolicy = (typeof TEAM_INVITATION_POLICIES)[number]

interface TeamFormValues {
  name: string
  slug?: string
  purpose?: string
  visibility: TeamVisibility
  invitationPolicy: TeamInvitationPolicy
  description?: string
  defaultRoleId?: string
  defaultRoleKey?: TeamRoleKey
}

export interface TeamInitialData {
  id: string
  name: string
  slug?: string | null
  purpose?: string | null
  visibility?: TeamVisibility
  invitationPolicy?: TeamInvitationPolicy
  description?: unknown
  defaultRole?: { id: string; key: TeamRoleKey } | null
  defaultRoleId?: string | null
  defaultRoleKey?: TeamRoleKey | null
}

const teamFormSchema = teamCreateBaseSchema.pick({
  name: true,
  slug: true,
  purpose: true,
  visibility: true,
  invitationPolicy: true,
  description: true,
  defaultRoleId: true,
  defaultRoleKey: true,
})

interface TeamFormProps {
  mode: 'create' | 'edit'
  organizationId: string
  teamId?: string
  initialData?: Partial<TeamInitialData>
  onCancel?: () => void
  onSuccess?: (team: unknown) => void
}

function normalizeDescription(value: unknown) {
  if (value === null || value === undefined) return ''
  if (typeof value === 'string') return value
  try {
    return JSON.stringify(value)
  } catch {
    return ''
  }
}

export function TeamForm({ mode, organizationId, teamId, initialData, onCancel, onSuccess }: TeamFormProps) {
  const router = useRouter()
  const toast = useToastController()
  const [hasAutoGeneratedSlug, setHasAutoGeneratedSlug] = useState(mode === 'create')

  const defaultValues = useMemo<TeamFormValues>(
    () => ({
      name: initialData?.name ?? '',
      slug: initialData?.slug ?? '',
      purpose: initialData?.purpose ?? '',
      visibility: (initialData?.visibility as TeamVisibility | undefined) ?? 'organization',
      invitationPolicy: initialData?.invitationPolicy ?? 'invite_only',
      description: normalizeDescription(initialData?.description),
      defaultRoleId: initialData?.defaultRoleId ?? initialData?.defaultRole?.id ?? undefined,
      defaultRoleKey: initialData?.defaultRoleKey ?? initialData?.defaultRole?.key ?? 'member',
    }),
    [
      initialData?.invitationPolicy,
      initialData?.defaultRole?.id,
      initialData?.defaultRole?.key,
      initialData?.defaultRoleId,
      initialData?.defaultRoleKey,
      initialData?.description,
      initialData?.name,
      initialData?.purpose,
      initialData?.slug,
      initialData?.visibility,
    ],
  )

  const {
    control,
    handleSubmit,
    getValues,
    formState: { errors, isDirty },
    setValue,
    reset,
  } = useForm<TeamFormValues>({
    resolver: zodResolver(teamFormSchema),
    defaultValues,
  })

  useEffect(() => {
    reset(defaultValues)
  }, [defaultValues, reset])

  const { roles, isLoading: isOptionsLoading } = useTeamFormOptions({
    organizationId,
  })

  // Auto-select default role when options load
  useEffect(() => {
    if (roles.length === 0) return

    const currentRoleId = getValues('defaultRoleId')
    const currentRoleKey = getValues('defaultRoleKey')

    if (currentRoleId && roles.some((role) => role.id === currentRoleId)) {
      if (!currentRoleKey) {
        const currentRole = roles.find((role) => role.id === currentRoleId)
        if (currentRole) {
          setValue('defaultRoleKey', currentRole.key, { shouldValidate: true })
        }
      }
      return
    }

    const defaultRole = roles.find((role) => role.key === 'member') ?? roles[0]
    setValue('defaultRoleId', defaultRole.id, { shouldValidate: true })
    setValue('defaultRoleKey', defaultRole.key, { shouldValidate: true })
  }, [roles, getValues, setValue])

  const createMutation = api.teams.create.useMutation({
    onSuccess: (data: { team?: unknown }) => {
      toast.show('Success', { message: 'Team created successfully' })
      onSuccess?.(data?.team)
      router.push(ROUTES.OFFICE_TEAMS.path)
    },
    onError: (error: Error) => {
      toast.show('Error', { message: error.message || 'Failed to create team' })
    },
  })

  const updateMutation = api.teams.update.useMutation({
    onSuccess: (data: { team?: unknown }) => {
      toast.show('Success', { message: 'Team updated successfully' })
      onSuccess?.(data?.team)
      router.push(ROUTES.OFFICE_TEAMS.path)
    },
    onError: (error: Error) => {
      toast.show('Error', { message: error.message || 'Failed to update team' })
    },
  })

  const isSubmitting = createMutation.isPending || updateMutation.isPending

  const handleNameChange = (value: string) => {
    setValue('name', value, { shouldValidate: true })
    if (mode === 'create' && hasAutoGeneratedSlug) {
      const generatedSlug = value
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
      setValue('slug', generatedSlug, { shouldValidate: true })
    }
  }

  const handleSlugChange = (value: string) => {
    setHasAutoGeneratedSlug(false)
    setValue('slug', value, { shouldValidate: true })
  }

  const onSubmit = async (values: TeamFormValues) => {
    const selectedRole = roles.find((role) => role.id === values.defaultRoleId)
    const resolvedDefaultRoleKey =
      values.defaultRoleKey ?? selectedRole?.key ?? teamRoleKeySchema.parse('member')

    const payloadBase = {
      organizationId,
      name: values.name.trim(),
      slug: values.slug?.trim() || undefined,
      purpose: values.purpose?.trim() || undefined,
      visibility: values.visibility,
      invitationPolicy: values.invitationPolicy,
      description: values.description?.trim() || undefined,
      defaultRoleId: values.defaultRoleId ?? selectedRole?.id,
      defaultRoleKey: resolvedDefaultRoleKey,
    }

    if (mode === 'create') {
      const createPayload: TeamCreateInput = {
        ...payloadBase,
        metadata: {},
      }
      await createMutation.mutateAsync(createPayload)
    } else {
      if (!teamId) {
        toast.show('Error', { message: 'Missing team identifier for update' })
        return
      }
      await updateMutation.mutateAsync({
        teamId,
        ...payloadBase,
      })
    }
  }

  const visibilityOptions = TEAM_VISIBILITIES.map((value) => ({
    value,
    label: value === 'organization' ? 'Organization' : 'Private',
  }))

  const invitationPolicyOptions = TEAM_INVITATION_POLICIES.map((value) => ({
    value,
    label: value === 'invite_only' ? 'Invite Only' : 'Request to Join',
  }))

  const renderContent = () => (
    <YStack gap="$4" width="100%" maxW={640} self="center">
      <Controller
        name="name"
        control={control}
        render={({ field }) => (
          <YStack gap="$2">
            <Label htmlFor="team-name">Name *</Label>
            <Input
              id="team-name"
              testID='team-form-name'
              value={field.value}
              onChangeText={handleNameChange}
              placeholder="Field Ops Team"
              borderColor={errors.name ? '$red8' : '$borderColor'}
            />
            {errors.name && (
              <Text color="$red10" fontSize="$2">
                {errors.name.message}
              </Text>
            )}
          </YStack>
        )}
      />

      <Controller
        name="slug"
        control={control}
        render={({ field }) => (
          <YStack gap="$2">
            <Label htmlFor="team-slug">Slug *</Label>
            <Input
              id="team-slug"
              testID='team-form-slug'
              value={field.value ?? ''}
              onChangeText={handleSlugChange}
              placeholder="field-ops-team"
              borderColor={errors.slug ? '$red8' : '$borderColor'}
            />
            <Text fontSize="$2" color="$color11">
              Lowercase, URL friendly identifier for the team
            </Text>
            {errors.slug && (
              <Text color="$red10" fontSize="$2">
                {errors.slug.message}
              </Text>
            )}
          </YStack>
        )}
      />

      <Controller
        name="purpose"
        control={control}
        render={({ field }) => (
          <YStack gap="$2">
            <Label htmlFor="team-purpose">Purpose</Label>
            <Input
              id="team-purpose"
              testID='team-form-purpose'
              value={field.value ?? ''}
              onChangeText={(value) => field.onChange(value)}
              placeholder="e.g. Hiring for Southeast operations"
            />
            {errors.purpose && (
              <Text color="$red10" fontSize="$2">
                {errors.purpose.message}
              </Text>
            )}
          </YStack>
        )}
      />

      <Controller
        name="visibility"
        control={control}
        render={({ field }) => (
          <YStack gap="$2">
            <Label>Visibility</Label>
            <Select value={field.value} onValueChange={field.onChange} disablePreventBodyScroll>
              <Select.Trigger iconAfter={ChevronDown} testID='team-form-visibility'>
                <Select.Value placeholder="Select visibility" />
              </Select.Trigger>
              <Select.Content zIndex={200000}>
                <Select.ScrollUpButton />
                <Select.Viewport>
                  <Select.Group>
                    <Select.Label>Visibility options</Select.Label>
                    {visibilityOptions.map((option, index) => (
                      <Select.Item key={option.value} value={option.value} index={index}>
                        <Select.ItemText>{option.label}</Select.ItemText>
                        <Select.ItemIndicator>
                          <Check size={16} />
                        </Select.ItemIndicator>
                      </Select.Item>
                    ))}
                  </Select.Group>
                </Select.Viewport>
                <Select.ScrollDownButton />
              </Select.Content>
            </Select>
            {errors.visibility && (
              <Text color="$red10" fontSize="$2">
                {errors.visibility.message}
              </Text>
            )}
          </YStack>
        )}
      />

      <Controller
        name="invitationPolicy"
        control={control}
        render={({ field }) => (
          <YStack gap="$2">
            <Label>Invitation Policy</Label>
            <Select value={field.value} onValueChange={field.onChange} disablePreventBodyScroll>
              <Select.Trigger iconAfter={ChevronDown} testID='team-form-invitation-policy'>
                <Select.Value placeholder="Select invitation policy" />
              </Select.Trigger>
              <Select.Content zIndex={200000}>
                <Select.ScrollUpButton />
                <Select.Viewport>
                  <Select.Group>
                    <Select.Label>Invitation policy</Select.Label>
                    {invitationPolicyOptions.map((option, index) => (
                      <Select.Item key={option.value} value={option.value} index={index}>
                        <Select.ItemText>{option.label}</Select.ItemText>
                        <Select.ItemIndicator>
                          <Check size={16} />
                        </Select.ItemIndicator>
                      </Select.Item>
                    ))}
                  </Select.Group>
                </Select.Viewport>
                <Select.ScrollDownButton />
              </Select.Content>
            </Select>
            {errors.invitationPolicy && (
              <Text color="$red10" fontSize="$2">
                {errors.invitationPolicy.message}
              </Text>
            )}
          </YStack>
        )}
      />

      <Controller
        name="description"
        control={control}
        render={({ field }) => (
          <YStack gap="$2">
            <Label htmlFor="team-description">Description</Label>
            <TextArea
              id="team-description"
              testID='team-form-description'
              value={field.value ?? ''}
              onChangeText={(value) => field.onChange(value)}
              placeholder="Add context about this team"
              rows={4}
            />
            {errors.description && (
              <Text color="$red10" fontSize="$2">
                {errors.description.message as string}
              </Text>
            )}
          </YStack>
        )}
      />

      <Controller
        name="defaultRoleId"
        control={control}
        render={({ field }) => (
          <YStack gap="$2">
            <Label>Default Role</Label>
            <Select
              value={field.value ?? ''}
              onValueChange={(value) => {
                field.onChange(value)
                const role = roles.find((item) => item.id === value)
                if (role) {
                  setValue('defaultRoleKey', role.key, { shouldValidate: true })
                }
              }}
              disablePreventBodyScroll
            >
              <Select.Trigger iconAfter={ChevronDown} testID='team-form-default-role'>
                <Select.Value placeholder="Select default role" />
              </Select.Trigger>
              <Select.Content zIndex={200000}>
                <Select.ScrollUpButton />
                <Select.Viewport>
                  <Select.Group>
                    <Select.Label>Team roles</Select.Label>
                    {roles.map((role, index) => (
                      <Select.Item key={role.id} value={role.id} index={index}>
                        <Select.ItemText>{role.name}</Select.ItemText>
                        <Select.ItemIndicator>
                          <Check size={16} />
                        </Select.ItemIndicator>
                      </Select.Item>
                    ))}
                  </Select.Group>
                </Select.Viewport>
                <Select.ScrollDownButton />
              </Select.Content>
            </Select>
            {errors.defaultRoleId && (
              <Text color="$red10" fontSize="$2">
                {errors.defaultRoleId.message as string}
              </Text>
            )}
          </YStack>
        )}
      />

      <XStack gap="$2" justify="flex-end">
        <Button
          theme="gray"
          variant="outlined"
          onPress={onCancel ?? (() => router.back())}
          disabled={isSubmitting}
          testID='team-form-cancel'
        >
          Cancel
        </Button>
        <Button
          onPress={handleSubmit(onSubmit)}
          disabled={isSubmitting || !isDirty}
          testID='team-form-submit'
        >
          {isSubmitting ? 'Saving…' : mode === 'create' ? 'Create Team' : 'Save Changes'}
        </Button>
      </XStack>
    </YStack>
  )

  if (isOptionsLoading && roles.length === 0) {
    return (
      <YStack flex={1} items="center" justify="center" p="$6">
        <Spinner size="large" />
        <Text mt="$4">Loading team options…</Text>
      </YStack>
    )
  }

  return (
    <ScrollView flex={1} bg="$color2" p="$5" showsVerticalScrollIndicator={false}>
      {renderContent()}
    </ScrollView>
  )
}

