-- =========================================================
-- 336_fix_validate_oauth_scope.sql — NEUTRALIZED, INTENTIONALLY A NO-OP.
--
-- This migration was never applied to any environment, and running it now
-- would reintroduce an authorization bypass. Its body has been removed rather
-- than left in place behind a warning comment, because a warning only helps
-- someone who reads it.
--
-- What it did
-- -----------
-- Migration 220 defined core.validate_oauth_scope with a join against
-- core.role_permissions / core.permissions — tables that never existed in this
-- schema (team management created core.team_role_permissions instead). Every
-- call raised, so OAuth /authorize 403'd on every request.
--
-- 336 removed the dead join, and authorized any scope whose rbac_permissions
-- array was empty. Every scope in the catalog had exactly that, so the effect
-- was to authorize any catalog scope for any authenticated user — including
-- ones flagged is_sensitive, such as organizations:write and documents:delete.
--
-- Why it is empty rather than deleted
-- -----------------------------------
-- Deleting the file would leave a gap that reads like an accident, and this
-- number is referenced from issue #428, from 338's header, and from the
-- discussion of the migration ledger in #437. Keeping the slot with an
-- explanation is more useful than either a silent gap or a live footgun. The
-- original SQL is in git history if it is ever needed.
--
-- What replaced it
-- ----------------
-- 338_oauth_scope_real_authorization.sql. It makes an undeclared requirement
-- mean *denied* rather than *open*, via an explicit is_self_scoped flag, and
-- classifies both of the live scope vocabularies (see its header). That is the
-- migration to read, and the one production actually runs.
--
-- Verified 2026-07-30: the deployed core.validate_oauth_scope contains
-- is_self_scoped, which only 338 introduces — proof 336's body never ran.
-- =========================================================

-- Intentionally no statements.
SELECT 1 WHERE FALSE;
