export * from './Chips'
export * from './ChipsNoTextColor'
export * from './ChipsRounded'
export * from './ChipsWithCloseIcon'
export * from './ChipsWithIcon'
export * from './FilterChip'
export { Chip } from './components/chipsParts'
